# Generated by Django 4.0.4 on 2022-04-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.admin')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.director')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoristMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.laboratorist')),
            ],
        ),
        migrations.CreateModel(
            name='NurseMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.receptionist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistMore',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auser.specialist')),
            ],
        ),
    ]
