# Generated by Django 4.0.4 on 2022-04-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
