# Generated by Django 4.0.4 on 2022-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistmore',
            name='User',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NU', 'Nurse'), ('PA', 'Patient'), ('LAB', 'LaboratorIST'), ('RT', 'Receptionist'), ('AD', 'Admin'), ('DI', 'Director'), ('PH', 'Pharmacist')], max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='SpecialistMore',
        ),
    ]
