# Generated by Django 4.0.4 on 2022-04-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_adminmore_directormore_doctormore_laboratoristmore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NU', 'Nurse'), ('SP', 'Specialist'), ('PA', 'Patient'), ('LAB', 'LaboratorIST'), ('RT', 'Receptionist'), ('AD', 'Admin'), ('DI', 'Director'), ('PH', 'Pharmacist')], max_length=50, verbose_name='Type'),
        ),
    ]
