# Generated by Django 4.0.4 on 2022-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='craftcraft', max_length=128, verbose_name='password'),
        ),
    ]
