# Generated by Django 4.0.4 on 2022-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0003_remove_specialistmore_user_delete_specialist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmore',
            name='User',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Hospital Manager'},
        ),
        migrations.AlterModelOptions(
            name='adminmore',
            options={'verbose_name': 'Hospital Manager More', 'verbose_name_plural': "Hospital Manager's More"},
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NU', 'Nurse'), ('LAB', 'LaboratorIST'), ('RT', 'Receptionist'), ('AD', 'Admin'), ('DI', 'Director'), ('PH', 'Pharmacist')], max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='PatientMore',
        ),
    ]
