# Generated by Django 4.0.4 on 2022-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DR', 'Doctor'), ('NU', 'Nurse'), ('LAB', 'Laboratorist'), ('RT', 'Receptionist'), ('HM', 'Hospital Manager'), ('DI', 'Director'), ('PH', 'Pharmacist'), ('HMS', 'HMS')], default='HMS', max_length=50, verbose_name='Type'),
        ),
    ]
